version: '3'

services: 
  app:
    build: 
      context: node-app
    container_name: app
    entrypoint: [ "dockerize", "-wait", "tcp://db:3306", "-timeout", "120s", "node", "index.js" ]
    networks: 
      - node-network
    volumes: 
      - /usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
      - db

  nginx:
    build: 
      context: nginx
    container_name: nginx
    entrypoint: [ "dockerize", "-wait", "tcp://app:3000", "-timeout", "120s", "nginx", "-g", "daemon off;" ]
    restart: always
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=services
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d/

networks: 
  node-network:
    driver: bridge
